name: Terraform Apply

on:
  push:
    branches: [ "master" ]
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Format
        id: fmt
        run: terraform fmt
      
      - name: Terraform Initialize
        id: init
        run: |
          terraform init \
          -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.AWS_SECRET_KEY }}" \
          -backend-config="role_arn=${{ secrets.AWS_ARN_ROLE }}"
      
      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve \
          -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
          -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}" \
          -var="sandbox_arn_role=${{ secrets.AWS_ARN_ROLE }}"
