name: Terraform Setup Validation

on:
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Format
        id: init
        run: terraform fmt
#      - name: Terraform Initialize

#      - name: Terraform Validation

#      - name: Terraform Plan
