name: Terraform Setup Validation

on:
  pull_request:
    branches: [ "master" ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Format
        id: fmt
        run: terraform fmt
      - name: Terraform Initialize
        id: init
        run: terraform init -backend-config="access_key= ${{ secrets.AWS_ACCESS_KEY }}"
#      - name: Terraform Validation

#      - name: Terraform Plan
