name: Terraform Setup Validation

on:
  pull_request:
    branches: [ "master" ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Format
        id: fmt
        run: terraform fmt
      
      - name: Terraform Initialize
        id: init
        run: |
          terraform init \
          -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.AWS_SECRET_KEY }}" \
          -backend-config="role_arn=${{ secrets.AWS_ARN_ROLE }}"
      
      - name: Terraform Validation
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
          -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
          -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}" \
          -var="sandbox_arn_role=${{ secrets.AWS_ARN_ROLE }}" \
          -out plan.out
          terragrunt show -no-color plan.out > plan.txt

      - name: PR Comment
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            const output = `
            #### Terragrunt Plan \`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`${fs.readFileSync('./plan.txt')}\`\`\`
            </details>`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
